# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 562af853bd4a4af7bb8098c6461ccac050562988393250807339ff45b53f182d4fcd6214674fb139a2b4a4045e5accc288bd9a16937c396fa4442e80bcba602d

test:
  secret_key_base: d81ab3a9ec3b47df71d02106cfea891501c881e9c968d40b74fb8d68dc359bb52bb9d58cc904da912f932d2623456497ad93f74f98a9f93acf6721dd1fb1d091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
